### ISSUE TITLE
Responsive Layout (too much width on mobile devices)

### ISSUE THREAD

**Issue by mhellmeier** [posativ/isso#931]
## Checklist
- [x] I am running the latest version. Installing Isso from GitHub from the `master` branch does not fix my issue
- [x] I have checked the [troubleshooting guide](https://isso-comments.de/docs/guides/troubleshooting/)
- [x] I have searched the [open issues](https://github.com/posativ/isso/issues), but my issue has not already been reported

## What is not working?

Isso isn't fully responsive. When viewing comments on a mobile device, the width is too large and content cannot fully displayed.

## How can one reproduce this issue?

See, for example, https://return2.net/laravel-auth-custom-login-validation/ on your mobile device or in a browser using the developer tools. Most comments aren't displayed correctly at the bottom of the page.

**Comment by ix5** [comment]
Your site looks fine to me even with width reduced to 300px on Firefox responsive view.

Could you add a screenshot of the exact comment you're referring to? Or is your issue that the code elements your commenters pasted are not rendering as code blocks?

**Comment by mhellmeier** [comment]
I just made a screenshot in the Google Chrome developer tools with the responsive view set to _iPhone 12 Pro_:


![Example](https://user-images.githubusercontent.com/1036284/197415371-6b37f25f-1ab8-4d1f-ada5-015eca41adac.png)

The form and long comments are too big for the small screen size.

**Comment by ix5** [comment]
It's your own custom css causing this (weirdly only on chrome):
```javascript
// Workaround isso issue: https://github.com/posativ/isso/issues/815
    $( "<style>#isso-thread { display: table; width: 100%; } #isso-root { display: table-footer-group; }</style>" ).appendTo( "head" );
```
Remove this, https://github.com/posativ/isso/issues/815 is resolved.

**Comment by mhellmeier** [comment]
Thanks for the hint but it doesn't solve the problem because really long words (for example this/very/very/very/very/very/very/very/very/very/very/very/very/long/path/on/my/personal/computer/) will crash the max width.

I will solve it in a small pull request!
